# Generated by Django 5.2.5 on 2025-09-05 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='address',
        ),
        migrations.RemoveField(
            model_name='application',
            name='email',
        ),
        migrations.RemoveField(
            model_name='application',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='application',
            name='portfolio_url',
        ),
    ]
