# Generated by Django 5.2.5 on 2025-09-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_remove_application_address_remove_application_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='created_at',
            new_name='applied_at',
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('interviewed', 'Interviewed'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='applied', max_length=20),
        ),
    ]
